### ISSUE TITLE
存储卡类型错误

### ISSUE THREAD

**Issue by Thons** [open-ai-robot/NVIDIA-JetBot-Diy#1]
Jetson Nano 需要的是 MicroSD 卡，链接中是闪迪的 SD 卡。
这里是符合读写速度要求的闪迪 64GB MicroSD 卡链接： https://detail.tmall.com/item.htm?id=579310557286&skuId=4149701839413

**Comment by unbug** [comment]
感谢纠正，你知道哪里有合适的3D打印吗？机器人的模具需要3D打印

**Comment by Thons** [comment]
这个没有详细了解过，我看淘宝上有卖家做这个，试试？

**Comment by unbug** [comment]
好，我研究一下，还帮看看其他的零件对不对得上，SD 卡已更新

**Comment by Thons** [comment]
除了那一条直角弯母天线座1.13端子线我没看明白，其它的暂没有发现问题。不过还是要花钱把所有列出的部件买来，组装起来才能最终确定是否有问题。等 Jetson Nano 到手之后看看吧。
对于接入前段时间发布的 Azure Kinect 摄像头，你怎么看？

**Comment by unbug** [comment]
现在已经还差磨具了，我其实都还没买，你是做AI方向的吗？我还有一个项目现在在设计阶段，感兴趣可以参与https://forums.anki.com/t/anki-vector-places-shoes-with-machine-learning/32014

**Comment by unbug** [comment]
上面的链接需要注册，你看这个吧 https://github.com/unbug/Anki-Vector-AI#shoes-placed

**Comment by Thons** [comment]
很遗憾，我是 NLP ，对 CV 只是关注ing

**Comment by unbug** [comment]
没关系，都是相通的，参与进来很多事可以做，写写文档，找找论文，贴贴资料都是有帮助的

**Comment by unbug** [comment]
或者可以推荐同事同学来参与

**Comment by Thons** [comment]
好，我会持续关注的
