### ISSUE TITLE
零件咨询

### ISSUE THREAD

**Issue by jetta** [open-ai-robot/NVIDIA-JetBot-Diy#2]
感谢您的汇总！有两个问题请教：
1. 60mm wheel for "TT motor"， 这个mouser.cn上无货，有其它可以替代的型号么？
2. USB cables， 这个转向是“左对右”还是“左对左”，长度0.14米够么？

谢谢！

**Comment by unbug** [comment]
1. mouser.cn 上60mm wheel for "TT motor" 确实没货，Taobao 不好找，我再找找。
2. USB 是右对右两个。

另外，我在和官方讨论要不要直接买智能小车模型替代，会省去3D打印的步骤，你可以去讨论, 这样轮子什么的都不用单独买了 https://github.com/NVIDIA-AI-IOT/jetbot/issues/12#issuecomment-477106652
或参看 https://github.com/unbug/NVIDIA-JetBot-Diy/wiki#3d-printed-components

**Comment by jetta** [comment]
@unbug 右对右的没货，怪不得我没找到。

**Comment by unbug** [comment]
左对右也差不多的，本身就扭一下

**Comment by jetta** [comment]
1-inch POM ball，跟淘宝卖家咨询了一下，100粒起拍，220元。

**Comment by unbug** [comment]
这么坑。。。可以去五金店自己买个看看

**Comment by unbug** [comment]
你找到好的卖家也欢迎贡献链接

**Comment by jetta** [comment]
我买回来先确认下能不能用

**Comment by unbug** [comment]
太棒了，欢迎更正链接

**Comment by AITCK** [comment]
必须吐槽下，官方使用的配件大多都是一些不常用的东西，要凑齐官方的配件不但贵还没不到，太难凑齐了。官方的方案不是一个很好的解决方法，非常Hard, 非常Hack，需要很强动手能力以及需要花费很多时间，比如要剪掉usb线，I2C接口需要用转接，而且还需要烙铁焊接。

@jetta @unbug 可以到我的淘宝店看看有没有你们需要的配件。

**https://shop214630955.taobao.com**

疑问解答：
1. 60mm轮子很难买的而且贵，推荐直接65mm轮子，官方已更新了65mm规格模型, 完美适用Jetbot。
2.建议使用0.25长度的usb线，0.14估计不行。至于右对右还是左对左影响不大。
3.我店里有 1-inch POM ball 实心球，既便宜又滑溜的
4.需要打印服务可以找我，配套螺丝包
5.加Jetbot技术交流群974447094，随时更新一些解决方案，比如 Jetbot Nano 电源供电问题。

**Comment by unbug** [comment]
谢谢 @wujupi ，确实不建议官方的套路，我在 WiKi 底部放了可以替换的小车模型，其实都是可以的，只需要驾好摄像头即可

**Comment by unbug** [comment]
@jetta 你能不能先试试我 WiKi 底部的小车模型？如果成功就没必要官方全部零件。

**Comment by unbug** [comment]
我新开了一个 issue, 欢迎讨论 https://github.com/open-ai-robot/NVIDIA-JetBot-Diy/issues/3

**Comment by jetta** [comment]
> 必须吐槽下，官方使用的配件大多都是一些不常用的东西，要凑齐官方的配件不但贵还没不到，太难凑齐了。官方的方案不是一个很好的解决方法，非常Hard, 非常Hack，需要很强动手能力以及需要花费很多时间，比如要剪掉usb线，I2C接口需要用转接，而且还需要烙铁焊接。
> 
> @jetta @unbug 可以到我的淘宝店看看有没有你们需要的配件。
> 
> **https://shop214630955.taobao.com**
> 
> 疑问解答：
> 
> 1. 60mm轮子很难买的而且贵，推荐直接65mm轮子，官方已更新了65mm规格模型, 完美适用Jetbot。
>    2.建议使用0.25长度的usb线，0.14估计不行。至于右对右还是左对左影响不大。
>    3.我店里有 1-inch POM ball 实心球，既便宜又滑溜的
>    4.需要打印服务可以找我，配套螺丝包
>    5.加Jetbot技术交流群974447094，随时更新一些解决方案，比如 Jetbot Nano 电源供电问题。

1. 😓，我买了65mm的轮子，Caster base 和 Caster shroud 估计都重新打印了；
3. 你这个球好，免运费。

**Comment by unbug** [comment]
@jetta 官方已经认可了 https://github.com/open-ai-robot/NVIDIA-JetBot-Diy/issues/3 ， 你可以直接试试
