### ISSUE TITLE
jetbot 的电机驱动iic接口应该和nano控制器的哪个接口相连呢？

### ISSUE THREAD

**Issue by sunkechenjing** [open-ai-robot/NVIDIA-JetBot-Diy#7]
已经基本做好jetbot了，不知道电机驱动的iic应该如何连接，我看到jetson nano上有两组iic，分别是sda1和scl， id-sda和id-scl。另外还有一个问题，就是我看到nano j41上有明确的5v，能否从这个5v接口给电机驱动板供电呢？

**Comment by unbug** [comment]
@revox0x @lcsama都成功组装了，你们回答一下

**Comment by revox0x** [comment]
1.我是按照官方的硬件安装教程装的，用的是sda1和scl1。
2.通过我的实验，可以通过gpio供电，但是会造成nano板子自身供电不足断电关机的问题，因为要做的是一个小车，为了方便是通过移动电源供电，在5v输出下，大多数移动电源单个USB最多输出2.4A的电流,最好还是通过另一个USB接口独立供电。

**Comment by sunkechenjing** [comment]
感谢unbug和revox0x，中午jetbot已经调试成功，jetbot能正常运转了。就差广角摄像头模块到货了。另外还买了一个gpu，试了一下模型的训练。现在有不少框架，cnn rcnn fast cnn，那种感觉模型比较好。有机会大家多分享

**Comment by unbug** [comment]
666，到 https://github.com/open-ai-robot/NVIDIA-JetBot-Diy/issues/6 发报名贴呀

**Comment by sunkechenjing** [comment]
666，nano没在身边，明早发

**Comment by sunkechenjing** [comment]
通过玩jetbot三天，照着老外的教程做了一遍nano检测和训练的实验，预感这个宝贝能玩出不少花样，其中还有不少迷没解开。digits6.1.1训练detectnet cocodog模型，验证是检测出了，在pc上不加框，但在nano上有框，但7只狗的照片，离得近的狗没有检测出。今天在网上查到谷歌有免费训练的云，好玩的事情太多了

**Comment by sunkechenjing** [comment]
今天按照github上的jetbot安装了广角摄像头，还没跑 jetbot识别程序 。但我试了之前 的官方 detectnet facenet程序发现，摄像头 取景 是反的。另外已经安装了风扇，风是向外吹的，jetson-nano发热量真大。各位试过广角摄像头吗？散热问题怎么解决呢？

**Comment by unbug** [comment]
散热量有这么大吗？可能detectnet facenet算法太慢
